name: Auto Update Page
on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - run: python build.py
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "chore: auto sync issues" || exit 0
          git push
